version: "3.1"

volumes:
  node-modules-evolver-backend:

networks:
  evolver-network:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    container_name: evolver-database
    networks:
      - evolver-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: evolver-database

  app:
    build:
      context: .
      target: dev
    container_name: evolver-backend
    entrypoint: dockerize -wait tcp://db:5432 -timeout 60s ./entrypoint.sh
    networks:
      - evolver-network
    volumes:
      - .:/usr/src/app
      - node-modules-evolver-backend:/usr/src/app/node_modules
    tty: true
    ports:
      - "3333:3333"
    environment:
      PORT: ${PORT:-3333}
      DATABASE_URL: "postgresql://root:root@db:5432/evolver-database?schema=public"
      NODE_ENV: ${NODE_ENV:-development}
      EXPIRES_IN: ${EXPIRES_IN:-1d}
      SECRET: ${SECRET:-mysecret123}
      SENTRY_DNS: ${SENTRY_DNS:-https://acb2435897645833cf4c54ed731785a1@o4506138692747264.ingest.sentry.io/4506138743209984}

    depends_on:
      - db
