version: "3.1"

volumes:
  node-modules-evolver-backend:

networks:
  evolver-network:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    container_name: evolver-database
    networks:
      - evolver-network
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: evolver-database

  app:
    build:
      context: .
      target: dev
    container_name: evolver-backend
    entrypoint: dockerize -wait tcp://db:5433 -timeout 60s ./entrypoint.sh
    networks:
      - evolver-network
    volumes:
      - .:/usr/src/app
      - node-modules-evolver-backend:/usr/src/app/node_modules
    tty: true
    ports:
      - "3333:3333"
      - "5555:5555"
    environment:
      PORT: ${PORT:-3333}
      DATABASE_URL: "postgresql://root:root@db:5433/evolver-database?schema=public"
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      - db
