name: Deploy Homolog
on:
    # push:
        # branches:
            # - homolog
    pull_request:
        branches:
            - homolog

jobs: 
    deploy:
        name: Deploy EC2
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - name: Copy file via ssh password
              uses: easingthemes/ssh-deploy@main
              with: 
                SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
                SOURCE: "./"
                REMOTE_HOST: ${{ secrets.SSH_HOST }}
                REMOTE_USER: ${{ secrets.SSH_USER }}
                TARGET: "/home/ubuntu/app/evolver-backend"
                EXCLUDE: "/.github/, /node_modules/"
              
